### ISSUE TITLE
error con el visualizador 

### ISSUE THREAD

**Issue by JRichi99** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#31]
Traceback (most recent call last):
  File "c:\programacion\IA\tarea-2-2023-1-JRichi99\DCColorSort\BallSortSolver.py", line 108, in <module>
    solver.game.make_move(step[0], step[1], moving_speed = MOVING_SPEED)
  File "c:\programacion\IA\tarea-2-2023-1-JRichi99\DCColorSort\BallSortBack.py", line 125, in make_move
    self.front.draw_move(self.current_state, from_idx, to_idx, moving_speed)
  File "c:\programacion\IA\tarea-2-2023-1-JRichi99\DCColorSort\BallSortFront.py", line 167, in draw_move
    ball_color = [x * 255 for x in  self.color_map(state.to_list()[from_idx][-1])[:3]]

Me aparece eso

**Comment by JRichi99** [comment]
Ademas me aparece error en un movimiento, ya que es no valido. Pero todos los movimientos los saco del metodo get_valid_moves()

**Comment by dfloreaa** [comment]
Hola @JRichi99 , podrías compartirme el error completo (algún pantallazo o algo similar)? De casualidad, ¿funciona con la visualización apagada?
